files:
  include: './src/assets/styles/*'
rules:
  indentation:
    - 2
    -
      size: 2
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-warn: 2
  leading-zero: 2
  space-after-comma: 2
  space-after-colon: 2
  space-before-brace: 2
  trailing-semicolon: 2
  final-newline: 2
  property-sort-order: 0
  no-url-protocols: 0
  no-url-domains: 0
  class-name-format: 0
  variable-name-format: 0
  mixins-before-declarations: 0
  mixin-name-format: 0
  no-vendor-prefixes: 0
