version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - "./src:/app/src"
    ports:
      - "9090:9090" # Потом прикрыть эти порты наружу
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - infrastructure
    command: >
      npm run start

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - .postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Потом прикрыть эти порты наружу
    env_file:
      - .env.prod
    networks:
      - infrastructure

networks:
  infrastructure:
    driver: bridge
    # external: true
    # driver: overlay
    # name: infrastructure
 
